#!/usr/bin/env bash

export packages=erg felix-bin crmsh ede yuki-iptv-bin etherpad-lite openspace openfaas-cli python-tensorly vaults domoticz xray-bin sherlock-git rustywind kipr kipr-git entropy tartufo livi oniongen-rs lok synth synth-git mlar ruget svd2rust cargo-ramdisk cargo-docset keydb cargo-benchcmp isolate doitlive emacs-spacemacs-funcs starlark-rust obsidian-export libcwtch-go libcwtch-go-git httpie-desktop-bin python-instagram-private-api cwtch cwtch-git cwtch-autobindings cwtch-autobindings-git cwtch-server cwtch-server-git cwtch-bin 
